name: Build and Deploy

on:
  push:
    branches:
      - main # Set a branch to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: Install Node.js
    - uses: actions/setup-node@v3
      with:
        node-version: '21'
    - run: npm install
    - run: npm test
